// Exemplo (se styles estiver na raiz de app)
import './styles/global.css'; 

// OU, se o Next.js criou styles fora de app, você usará o caminho relativo que funciona
// Ex: Se o CSS for global, a importação pode ser no 'layout.js' principal, e o Next.js
// gerado pelo `create-next-app` geralmente já faz isso corretamente.

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digitaly Hackaton",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
